apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80 # Cluster IP
      targetPort: 5173 # ตรงกับ containerPort
  type: NodePort
