apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-container
          image: my-frontend-app
          imagePullPolicy: Never # ใช้สำหรับ Minikube ที่ Image อยู่ในเครื่องเรา
          ports:
            - containerPort: 5173 # Port ที่ Frontend จะฟังอยู่
