apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-runner-secrets-manager
  namespace: default # กำหนด Namespace ที่ Runner ต้องการสร้าง Secret ในที่นี้คือ 'default'
rules:
  - apiGroups: [""] # "" หมายถึง Core API Group (เช่น Secrets, Pods, Services)
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch", "delete"] # สิทธิ์ที่ต้องการ: สร้าง, อ่าน, อัปเดต, ลบ Secret
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
