apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner-bind-secrets-manager
  namespace: default # RoleBinding นี้จะผูก Role เข้ากับ Service Account ใน Namespace นี้
subjects:
  - kind: ServiceAccount
    name: gitlab-runner # ชื่อ Service Account ของ GitLab Runner ของคุณ
    namespace: gitlab-runner # Namespace ที่ Service Account ของ Runner อยู่
roleRef:
  kind: Role
  name: gitlab-runner-secrets-manager
  apiGroup: rbac.authorization.k8s.io
