apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment # ชื่อ Deployment
  labels:
    app: backend-app
spec:
  replicas: 1 # รัน Backend 1 ชุดก่อน (สามารถเพิ่มเป็น 2, 3 ได้ภายหลัง)
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container # ชื่อของ Container ภายใน Pod
          image: my-backend-app # ชื่อ Docker Image ที่เราสร้างไว้ใน Step 2
          imagePullPolicy:
            Never # บอก Kubernetes ว่าไม่ต้องพยายามดึง Image จาก Docker Hub
            # เพราะเราสร้าง Image ไว้ในเครื่องเราแล้ว (ใช้ได้กับ Minikube)
          ports:
            - containerPort: 3026 # Port ที่ Backend ของเรารันอยู่ภายใน Container
