apiVersion: v1
kind: Service
metadata:
  name: backend-app-service # ชื่อ Service
spec:
  selector:
    app: backend-app # Service นี้จะเชื่อมต่อไปยัง Pods ที่มี label 'app: backend-app'
  ports:
    - protocol: TCP
      port: 5000 # Port ที่ Service จะเปิดรับ (ภายใน Cluster)
      targetPort: 3026 # Port ที่ Backend Container กำลังฟังอยู่
  type:
    NodePort # ประเภทของ Service: NodePort จะเปิด Port บน Node ของ Cluster
    # ทำให้เราเข้าถึงได้จากภายนอก
