###
GET http://localhost:3026/api/appointments/?page=1&limit=10&name=k
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUyMDcwOTExLCJleHAiOjE3NTIxNTczMTF9.ueAml6vRYlwttZ4lzr_zFpxdVQVAvfyNKahYAYIaZyE

###
GET http://localhost:3026/api/appointments/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUyMDcwOTExLCJleHAiOjE3NTIxNTczMTF9.ueAml6vRYlwttZ4lzr_zFpxdVQVAvfyNKahYAYIaZyE

###
GET http://localhost:3026/api/appointments/doctors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUyMDcwOTExLCJleHAiOjE3NTIxNTczMTF9.ueAml6vRYlwttZ4lzr_zFpxdVQVAvfyNKahYAYIaZyE
###
GET http://localhost:3026/api/appointments/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUyMDcwOTExLCJleHAiOjE3NTIxNTczMTF9.ueAml6vRYlwttZ4lzr_zFpxdVQVAvfyNKahYAYIaZyE
###
DELETE http://localhost:3026/api/appointments/30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUyMDcwOTExLCJleHAiOjE3NTIxNTczMTF9.ueAml6vRYlwttZ4lzr_zFpxdVQVAvfyNKahYAYIaZyE
